Repository AY2122S1-CS2103T-W11-3/tp, pull requests merged in 2021-11, with the labels that each got.

#211 PEDbugfixes
  docs/UserGuide.md
  src/main/java/manageme/logic/commands/ArchiveCommand.java
  src/main/java/manageme/logic/commands/link/AddLinkCommand.java
  src/main/java/manageme/logic/commands/link/EditLinkCommand.java
  src/main/java/manageme/logic/commands/task/AddTaskCommand.java
  src/main/java/manageme/logic/commands/task/EditTaskCommand.java
  src/main/java/manageme/model/link/LinkModule.java
  src/main/java/manageme/model/task/TaskModule.java
  src/main/resources/images/Command Summary.png
  src/main/resources/view/HelpWindow.fxml
  src/test/data/JsonSerializableManageMeTest/typicalManageMe.json
  src/test/java/manageme/logic/commands/link/AddLinkCommandTest.java
  src/test/java/manageme/logic/commands/task/TaskCommandTestUtil.java
  src/test/java/manageme/testutil/TypicalModules.java
Labels: type.Bug

#214 Taskmodeltestcases
  src/main/java/manageme/model/task/Task.java
  src/main/java/manageme/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/manageme/model/task/TaskDescriptionTest.java
  src/test/java/manageme/model/task/TaskIsDoneTest.java
  src/test/java/manageme/model/task/TaskModuleTest.java
  src/test/java/manageme/model/task/TaskNameTest.java
  src/test/java/manageme/model/task/TaskTest.java
  src/test/java/manageme/model/task/TaskTimeTest.java
Labels: type.Testing

#220 Updated PUML for UG
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MMStorageClassDiagram.puml
Labels: type.Documentation

#223 Fixeditdeletemodbug
  src/main/java/manageme/logic/commands/module/DeleteModuleCommand.java
  src/main/java/manageme/logic/commands/module/EditModuleCommand.java
  src/main/java/manageme/model/Model.java
  src/main/java/manageme/model/ModelManager.java
  src/main/java/manageme/model/link/LinkModule.java
  src/main/java/manageme/model/task/TaskModule.java
  src/test/java/manageme/logic/commands/link/AddLinkCommandTest.java
  src/test/java/manageme/logic/commands/module/AddModuleCommandTest.java
  src/test/java/manageme/logic/commands/module/DeleteModuleCommandTest.java
  src/test/java/manageme/logic/commands/task/AddTaskCommandTest.java
Labels: type.Bug

#234 Update PPP and DG
  docs/DeveloperGuide.md
  docs/diagrams/ManageMeModelClassDiagram.puml
  docs/team/markus.md
Labels: type.Documentation

#245 DGupdate
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskActivityDiagram.puml
  docs/diagrams/ArchiveActivityDiagram.puml
  docs/diagrams/DeleteDoneTaskSequenceDiagram.puml
  docs/diagrams/MMModelClassDiagram.puml
  docs/diagrams/MarkTaskSequenceDiagram.puml
  docs/images/AddTaskActivityDiagram.png
  docs/images/ArchiveActivityDiagram.png
  docs/images/DeleteDoneTaskSequenceDiagram.png
  docs/images/MarkTaskSequenceDiagram.png
Labels: type.Documentation

#246 DGupdate
  docs/DeveloperGuide.md
  docs/images/MMModelClassDiagram.png
Labels: type.Documentation

#247 fix model class diagram
  docs/DeveloperGuide.md
Labels: type.Documentation

#250 changed class diagram sizing
  docs/DeveloperGuide.md
Labels: type.Documentation

#275 DGupdate
  docs/DeveloperGuide.md
  docs/diagrams/MMModelClassDiagramNew.puml
  docs/images/MMModelClassDiagram.png
  docs/team/markuslim24.md
  src/main/java/manageme/model/task/Task.java
  src/main/java/manageme/model/task/TaskTime.java
Labels: type.Documentation

#278 DGupdate
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchiveActivityDiagram.puml
  docs/images/ArchiveActivityDiagram.png
  docs/team/markuslim24.md
  src/main/resources/images/Command Summary.png
Labels: type.Documentation

#289 Docsupdate
  docs/AboutUs.md
Labels: type.Documentation
