Repository AY2122S1-CS2103T-W11-3/tp, pull requests merged in 2021-10, with the labels that each got.

#86 Testing edit task logic+documentation update tasks in user guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/task/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TaskCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/task/EditTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
Labels: type.Documentation, type.Testing

#83 Add additional Task and Storage test cases.
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/task/TaskNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/data/JsonAddressBookStorageTest/Task/invalidAndValidTaskAddressBook.json
  src/test/data/JsonAddressBookStorageTest/Task/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/Task/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/Task/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/Task/typicalTasksAddressBook.json
  src/test/java/seedu/address/logic/commands/task/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TaskCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/task/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Documentation, type.Testing

#105 Update validation regex of Task models
  src/main/java/manageme/logic/parser/ParserUtil.java
  src/main/java/manageme/logic/parser/task/AddTaskCommandParser.java
  src/main/java/manageme/model/task/TaskDescription.java
  src/main/java/manageme/model/task/TaskModule.java
  src/main/java/manageme/model/task/TaskName.java
  src/main/java/manageme/model/task/TaskTime.java
  src/main/java/manageme/storage/JsonAdaptedTask.java
  src/main/java/manageme/ui/task/TaskCard.java
  src/test/data/JsonAddressBookStorageTest/Task/invalidAndValidTaskAddressBook.json
  src/test/data/JsonAddressBookStorageTest/Task/invalidTaskManageMe.json
  src/test/data/JsonSerializableManageMeTest/Task/invalidTaskManageMe.json
  src/test/java/manageme/logic/commands/task/TaskCommandTestUtil.java
  src/test/java/manageme/logic/parser/ParserUtilTest.java
  src/test/java/manageme/model/task/TaskDescriptionTest.java
  src/test/java/manageme/model/task/TaskModuleTest.java
  src/test/java/manageme/model/task/TaskNameTest.java
  src/test/java/manageme/model/task/TaskTimeTest.java
  src/test/java/manageme/storage/JsonAdaptedTaskTest.java
Labels: type.Chore

#113 update text(minor)
  docs/DeveloperGuide.md
Labels: type.Documentation

#114 Docs update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/diagrams/MMStorageClassDiagram.puml
  docs/diagrams/MMTimeClassDiagram.puml
  docs/diagrams/ManageMeModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteTaskSequenceDiagram.png
  docs/images/MMStorageClassDiagram.png
  docs/images/MMTimeClassDiagram.png
  docs/images/ManageMeModelClassDiagram.png
  docs/images/ParserClassesManageMe.png
  docs/images/UiClassDiagram.png
  src/main/java/manageme/MainApp.java
  src/main/java/manageme/commons/exceptions/TimeComparisonException.java
  src/main/java/manageme/logic/LogicManager.java
  src/main/java/manageme/model/ManageMe.java
  src/main/java/manageme/model/ModelManager.java
  src/main/java/manageme/model/ReadOnlyManageMe.java
  src/main/java/manageme/model/task/Task.java
  src/main/java/manageme/model/task/UniqueTaskList.java
  src/main/java/manageme/storage/JsonAdaptedTask.java
  src/main/java/manageme/time/Time.java
  src/main/java/manageme/time/TimeManager.java
  src/main/java/manageme/ui/MmMainWindow.java
  src/main/java/manageme/ui/UiManager.java
  src/main/java/manageme/ui/calendar/CalendarPanel.java
  src/main/java/manageme/ui/calendar/DayCard.java
  src/main/java/manageme/ui/module/ModuleListPanel.java
  src/main/java/manageme/ui/task/TaskCard.java
  src/main/java/manageme/ui/task/TaskListPanel.java
  src/main/resources/view/CalendarListPanel.fxml
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/DayCard.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/ManageMe.css
  src/main/resources/view/MmMainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/ModuleWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/manageme/logic/LogicManagerTest.java
  src/test/java/manageme/model/ManageMeTest.java
Labels: type.Documentation, type.Chore, type.Testing

#118 remove assert false in UiManager
  build.gradle
  src/main/java/manageme/ui/UiManager.java
Labels: type.Bug

#119 Dev
  build.gradle
  src/main/java/manageme/ui/UiManager.java
Labels: type.Bug
